wspring.application.name=SiteSync

spring.data.mongodb.uri=mongodb://localhost:27017/testdb

jwt.secret=oF9NmSqbtMa+ogf3hTTZEQ4k2tJvMoq1KQysc0XPJWg=
jwt.expiration=3600000

storage.upload-dir: ${UPLOAD_DIR:./uploads}


springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger-ui.html